<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UserFormulirSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('formulir')->insert([
            [
                'id_user' => 2,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'Pamungkas',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08321',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(8)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 3,
                'id_provinces' => 12,
                'id_cities' => 185,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'Jefrey',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08320',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(7)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 4,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'nichol end',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->addDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 5,
                'id_provinces' => 12,
                'id_cities' => 185,
                'id_districts' => 2063,
                'id_villages' => 31053,
                'nama' => 'samsul',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08323',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Teknik Cukur Dasar',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(5)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 6,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'arief',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08324',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Teknik Cukur Dasar',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(4)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 7,
                'id_provinces' => 12,
                'id_cities' => 185,
                'id_districts' => 2063,
                'id_villages' => 31053,
                'nama' => 'sunandar',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08325',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(3)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 2,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'asep',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08326',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Teknik Cukur Dasar',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(1)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 8,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => '	ajam muhtar',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08328',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Teknik Cukur Dasar',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(2)->format('Y-m-d H:i:s'),
            ],
            [
                'id_user' => 23,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'wiyanda wulandari',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(9)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 10,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'siti rahayu',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(7)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 11,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'sri septi mulyani',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 12,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'neng tesa epriliani',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 13,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'nisa',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 14,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'ade lisnia',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 15,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => '	popi fitriyani',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 16,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'yadi cahyadi	',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 17,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'rio lumkan gumbira',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 18,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'dadan iskandar',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 19,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => '	hendra nugraha',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(6)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 20,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => '	fitri siti fatimah',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(16)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 21,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => '	tati ratih herliati',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(15)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 22,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => '	Rita Tresna Agustina',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(14)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 23,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'maryono',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(13)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 24,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'aang sumpena',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(16)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 25,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'lugi sumarna',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(11)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 26,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'ikal',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(4)->format('Y-m-d H:i:s')
            ],
            [
                'id_user' => 27,
                'id_provinces' => 12,
                'id_cities' => 181,
                'id_districts' => 2558,
                'id_villages' => 31285,
                'nama' => 'dadi',
                'umur' => '25',
                'ttl' => 'Jakarta, 19 April 1999',
                'alamat' => 'Kampung Jeruk',
                'no_kk' => '',
                'no_ktp' => '',
                'jenis_kelamin' => 'Laki-laki',
                'pekerjaan' => 'Penyanyi',
                'pendidikan' => 'SMA',
                'angkatan' => '2020',
                'no_hp' => '08322',
                'no_rek' => '',
                'bank' => '',
                'atas_nama' => '',
                'peminatan' => 'Otomotif Service Sepeda Motor Ringan',
                'status' => 'Calon Peserta',
                'created_at' => Carbon::now()->subDays(10)->format('Y-m-d H:i:s')
            ],

        ]);
    }
}
